### YamlMime:FAQ
metadata:
  title: Organization FAQs
  titleSuffix: Azure DevOps
  description: Learn the answers to frequently asked questions (FAQs) about creating, deleting, restoring, and configuring your organization in Azure DevOps.
  ms.subservice: azure-devops-organizations
  ms.assetid: e0fe24d4-f76b-43af-b0fd-125a7fb39042
  ms.topic: faq
  ms.author: chcomley
  author: chcomley
  ms.date: 01/15/2025
  monikerRange: '<= azure-devops'
title: Organization FAQs
summary: |
  [!INCLUDE [version-lt-eq-azure-devops](../../includes/version-lt-eq-azure-devops.md)]
  
  Learn the answers to frequently asked questions (FAQs) about creating and configuring an organization in Azure DevOps, grouped into the following categories:
  
    - [General](#general-organization-faqs)
    - [Create an organization](#create-organization-faqs)
    - [Configure an organization](#configure-organization-faqs)
    - [Delete or restore an organization](#delete-restore-organization-faqs)
  
  For more information about user and permissions management, see [User and permissions management FAQs](faq-user-and-permissions-management.yml).
  
  <a name="general-organization-faqs"></a>

sections:
  - name: General
    questions:
      - question: |
          Q: Which users can join for free, and what benefits do they receive from joining Azure DevOps?
        answer: |
          A: Get the following benefits from joining Azure DevOps:

          [!INCLUDE [free-tier](../../includes/free-tier.md)]
          
          For more information, see [Azure DevOps pricing](https://azure.microsoft.com/pricing/details/devops/azure-devops-services/).
          
          <a name="browser-problems"></a>
          
      - question: |
          Q: Why won't my browser work with Azure DevOps?
        answer: |
          A: You might be using an unsupported browser. For the best experience, ensure you're using a [supported browser](/azure/devops/server/compatibility#supported-browsers).
          
      - question: |
          Q:  Which Visual Studio subscriptions can I use with Azure DevOps?
        answer: |
          A: [Find Visual Studio subscriptions that include Azure DevOps](faq-user-and-permissions-management.yml#EligibleMSDNSubscriptions).
          
      - question: |
          Q: How do I sign in to Azure DevOps if I forgot my organization name?
        answer: |
          A: If you forgot your organization name, [sign in to your Visual Studio profile](https://go.microsoft.com/fwlink/?LinkId=309329), where you can view a list of your organizations.

          <a name="organization-location"></a>
          
      - question: |
          Q: How do I find the geography where my organization is located? 
        answer: |
          A: [Find your organization's geography](./change-organization-location.md).
          
      - question: |
          Q: How do I change my project name, organization location, or project process? 
        answer: |
          A: See the following articles:
          
          - [Change your project name](../../organizations/projects/rename-project.md)
          - [Change your organization geography](./change-organization-location.md)
          - [Change your project process from Agile to Scrum](../../organizations/settings/work/change-process-agile-to-scrum.md)
          - [Change your project process from Scrum to Agile](../../organizations/settings/work/change-process-scrum-to-agile.md)
          - [Change your project process from Basic to Agile](../../organizations/settings/work/change-process-basic-to-agile.md)
          
          <a name="create-organization-faqs"></a>
          
          ## Create an organization

          For more information, see [Plan your Azure DevOps organization structure](../../user-guide/plan-your-azure-devops-org-structure.md?view=azure-devops).
      
      - question: |
          Q: Is localization supported in the Azure Devops service?
        answer: |
          A: Sorry, we don't support localization in the Azure DevOps service. We do support localization in the on-premises version of Azure DevOps.

      - question: |
          Q: How many organizations can I create?
        answer: |
          A: You can [create multiple organizations](#create-another-organization). But instead of creating another organization, you might consider [creating another project](#another-team-project). Your organization can have unlimited private projects by using Git or Microsoft Team Foundation Version Control.
          
          There's no limit to the number of organizations that you can join.  
          
      - question: |
          Q: Why are some features not available in my organization?
        answer: |
          A: Some features require you to install an extension, which might be available for free or paid.
          
          <a name="create-another-organization"></a>
          
      - question: |
          Q: How do I create another organization?
        answer: |
          A: [Create an organization](create-organization.md).
          
          <a name="another-team-project"></a>
          
      - question: |
          Q: Can I create more than one project?
        answer: |
          A: Yes, multiple projects help you keep work separate when you have development projects for different teams. Only one project collection is supported.
          
          For more information, see the following articles:
          - [About projects and scaling your organization](../projects/about-projects.md)
          - [Create a project](../projects/create-project.md)
          
      - question: |
          Q: Can I delete a project that I created?
        answer: |
          A: Yes, you can [delete a project](../projects/delete-project.md) that you don't use anymore.
          
      - question: |
          Q: Can I delete an organization that I don't need anymore? 
        answer: |
          A: Yes. See [Delete or recover your organization](./delete-your-organization.md).
          
          <a name="SignInOrganizationDifferences"></a>
          
      - question: |
          Q: What's the difference between using a Microsoft account and a work or school account to sign up?
        answer: |
          A: Your choice of account type affects how you control access and authenticate users for your organization.
          
          When you sign up with a Microsoft account:
          
          * You're solely responsible for managing access to your organization.
          * All users must sign in with Microsoft accounts.
          
          When you sign up with a work or school account:
          
          * Your organization is automatically connected to your directory in Microsoft Entra ID.
          * All users must be members in the connected directory to get access to your organization.
          * The directory administrator has control over who can join the directory.
          * You sign in with work or school accounts, or with Microsoft accounts if your company allows that.
          
          To [add users to the directory](/azure/active-directory/active-directory-create-users), be a directory administrator. If you can't access, work with your directory administrator to add users. Learn more about [work or school accounts for your organization](/azure/active-directory/sign-up-organization).
          
          <a name="ChooseOrgAcctMSAcct"></a>
          
          [!INCLUDE [choose-msa-azuread-account](../../includes/qa-choose-msa-azuread-account.md)]
          
          * Choose **Work or school account** if you want to use your directory to authenticate users and control organization access. This option limits access to members in your organization's directory. In this case, all other users also must sign in with work or school accounts. 
          
          * Choose **Personal account** if you want to use your Microsoft account with Azure DevOps. In this case, all other users also must sign in with Microsoft accounts.
          
          [!INCLUDE [why-cant-sign-in-msa-azuread-account](../../includes/qa-why-cant-sign-in-msa-azuread-account.md)]
        
          <a name="ChangeDirectory"></a>

      - question: |
          Q: Can I change the directory after sign-in?
        answer: |
          A: Yes, see [Disconnect your organization from Microsoft Entra ID](disconnect-organization-from-azure-ad.md) and  [Connect your organization to Microsoft Entra ID](connect-organization-to-azure-ad.md).
      
      - question: |
          Q: How do you store, secure, and protect my data?
        answer: |
          A: See the [Data protection overview](../security/data-protection.md).
          
      - question: |
          Q: Do I still own my code and intellectual property? What do you do with my personal information?
        answer: |
          A: Yes, your code and your intellectual property are yours. Review our [terms of service](https://go.microsoft.com/fwlink/?LinkID=266231) and [privacy policy](https://go.microsoft.com/fwlink/?LinkID=264782).
          
      - question: |
          Q: Where can I find the Azure DevOps Service Level Agreement (SLA)?
        answer: |
          A: You can find it here: [Azure DevOps SLA](https://azure.microsoft.com/support/legal/sla/visual-studio-team-services/v1_2/).
          
      - question: |
          Q: I'm having problems with my Visual Studio subscription. How can I get help?
        answer: |
          A: You can try [Subscription Support](https://visualstudio.microsoft.com/support/subscription-support-vs) or for more information, see [Set up Visual Studio FAQs](faq-set-up-vs.yml). 
                    
          <a name="configure-organization-faqs"></a>
          
  - name: Configure an organization
    questions:
      - question: |
          Q: Why can't I find the user who I want to make the new owner?
        answer: |
          A: You might not find the user for one of the following reasons:
          
          * The user isn't in your organization, or the user doesn't have organization access. Learn how to [add a user to your organization](add-organization-users.md).  
          * The user didn't create a Visual Studio profile or agree to the Terms of Service.  
          * If you recently added this person to your organization, you might experience a delay before the user appears in the possible organization owners list.  
          * If your organization uses Microsoft Entra ID to control access, directory members don't appear in the possible organization owners list until they meet the requirements. For more information, see [Access Microsoft Entra FAQs](faq-azure-access.yml).
          
      - question: |
          Q: What if the owner of my organization left the company/isn't active?
        answer: |
          A: Azure DevOps Administrators can claim ownership of organizations where the current owner and any members of the Project Collection Administrators group are inactive in the Microsoft Entra tenant connected to your organization. For more information, see [Resolve inactive organization owner](resolve-orphaned-organization.md).
          
      - question: |
          Q: Can I change my organization owner?
        answer: |
          A: Yes. If you're a Project Collection Administrator, you can change the organization owner in your organization settings. For more information, see [Change the organization owner](./change-organization-ownership.md).
          
      - question: |
          Q: Can I change the organization name (URL)?
        answer: |
          A: Only the organization owner can change the URL. If you're the organization owner, see [Rename your organization](./rename-organization.md).
          
      - question: |
          Q: Can I reverse an organization owner change?
        answer: |
          A: Yes, if you're a Project Collection Administrator.
          
      - question: |
          Q: How many organization owners can I have?
        answer: |
          A: Your organization can have only one owner. Only organization owners can [do certain actions](#owner-differences), so make sure you keep your organization owner updated.
          
      - question: |
          Q: Can I assign a new owner to my organization when the current owner is no longer active?
        answer: |
          A: Yes. For more information, see [Resolve orphaned organization ownership](resolve-orphaned-organization.md).
          
      - question: |
          Q: Why did you ask for extra information when I signed in?
        answer: |
          A: If our Terms of Service changed since you last signed in, you might need to agree and confirm that your information is up to date.
          
          <a name="owner-differences"></a>
          
      - question: |
          Q: When I change ownership from myself (as PCA) to a different user, my own account gets removed from the PCA group. Is this behavior a bug?
        answer: |
          A: No, this behavior isn't a bug and is currently by design, although we hope to address this behavior soon.
          
      - question: |
          Q: What makes the organization owner different from other organization users?
        answer: |
          A: The organization owner can do the following tasks, which other users don't have permissions to do: 
          
          - Manage billing in the [Azure portal](https://ms.portal.azure.com/#home)
          - [Pay for users to access the organization](../billing/buy-basic-access-add-users.md)
          - [Pay for more organization services](../billing/try-additional-features-vs.md)
          - [Rename the organization URL](./rename-organization.md)
          - [Change the organization owner](./change-organization-ownership.md)
          - [Recover a deleted organization](./recover-your-organization.md)
          
          Project collection administrators (PCAs) can perform all actions done by organization owners, except for recovering a deleted organization, which is a current limitation we're working to resolve.
          
      - question: |
          Q: Why don't I see the organizations that I own after I sign in to my Visual Studio profile on visualstudio.com?
        answer: |
          A: Your list of organizations is associated with the identity that you use to sign in to Azure DevOps.
          
          If you're asked to choose between your personal Microsoft account or your work or school account when you sign in, maybe you selected the wrong identity.
          
          Try to sign out completely from Azure DevOps, then sign in again and select your other identity.
          
          Closing your browser doesn't always sign you out completely. Here's how you can sign out completely:
          
          1. Close all browsers, including browsers that aren't running Azure DevOps.
          
          2. Open a private or incognito browsing session. 
          
          3. Go to this URL: `https://aka.ms/vssignout`.
          
             You see the message "Sign out in progress." After you sign out, you're redirected to the Visual Studio page @visualstudio.microsoft.com. 
          
             > [!Tip]
             > If the sign-out page takes more than a minute to sign you out, close the browser and continue.
          
          4. Sign in to Azure DevOps again. Select your other identity.
                    
          <a name="delete-restore-organization-faqs"></a>
          
  - name: Delete or restore your organization
    questions:
      - question: |
          Q: How do I delete my organization?
        answer: |
          A: See [Delete your organization](delete-your-organization.md), which includes prerequisites, precautions, and helpful tips.
          
      - question: |
          Q: How do I restore my organization?
        answer: |
          A: See [Recover your organization](./recover-your-organization.md).
          
          <a name="get-support"></a>
          
          [!INCLUDE [get-team-services-support](../../includes/qa-get-vsts-support.md)]
          
additionalContent: |

  ## Related articles
  
  - [Access with Microsoft Entra FAQ](faq-azure-access.yml)
  - [Set up Visual Studio FAQ](faq-set-up-vs.yml)
  - [User and permissions management FAQ](faq-user-and-permissions-management.yml)
